Config = {
    USE_ESSENTIALMODE_ADMIN_SYSTEM = true,
    -- only if USE_ESSENTIALMODE_ADMIN_SYSTEM is set to false
    ADMINS = {"steam:110000103cf1d19"},
    CONTROL_TO_OPEN_PANEL = 10,
    CONTROL_TO_ADD_POINT = 182,
    CONTROL_TO_REMOVE_LAST_POINT = 178,
}